# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 1
update_configs:
    - package_manager: "java:gradle"
      directory: "./ApiDemos/java/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./ApiDemos/kotlin/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./WearOS/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./tutorials/java/CurrentPlaceDetailsOnMap/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./tutorials/kotlin/CurrentPlaceDetailsOnMap/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./tutorials/java/MapWithMarker/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./tutorials/kotlin/MapWithMarker/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./tutorials/java/Polygons/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./tutorials/kotlin/Polygons/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./tutorials/java/StyledMap/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"

    - package_manager: "java:gradle"
      directory: "./snippets/"
      update_schedule: "weekly"
      commit_message:
          prefix: "chore(deps)"
